'use strict';
const D=window.CO_DATA;
if(!D){document.querySelector('main').innerHTML='<h1>No se pudieron cargar los resultados</h1><p>Comprueba que data.js esté disponible junto a la aplicación. No se muestran datos de ejemplo.</p>';throw new Error('Missing dataset');}
const $=id=>document.getElementById(id), fmt=(v,d=1)=>v==null?'Sin dato':v.toLocaleString('es-PE',{minimumFractionDigits:d,maximumFractionDigits:d});
const stationMap=new Map(D.stations.map(s=>[s.id,s])), metricMap=new Map(D.metrics.map(m=>[m.station,m])), records=new Map(D.pairs.map(r=>[`${r.station}|${r.time}`,r]));
let state={station:'SANTA_ANITA',index:0,view:'explorar'}, timer=null;
const maxSim=Math.max(...D.pairs.map(r=>r.sim));
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
$('station').innerHTML=D.stations.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('');
$('hour').innerHTML=[1,4,7,10,13,16,19,22].map(h=>`<option value="${String(h).padStart(2,'0')}">${String(h).padStart(2,'0')}:00</option>`).join('');
$('map-list').innerHTML=D.stations.map(s=>`<button data-station="${s.id}">${esc(s.name)}</button>`).join('');
$('quality-table').innerHTML=D.stations.map(s=>{const m=metricMap.get(s.id);return `<tr><td>${esc(s.name)}</td><td>${m.n} / 248</td><td>${fmt(m.coverage*100)} %<div class="bar"><span style="width:${m.coverage*100}%"></span></div></td><td class="${s.maintenance?'quality-warn':''}">${s.maintenance?'Mantenimiento reportado':'Sin advertencia reportada'}</td></tr>`}).join('');
$('version').textContent=D.version;
$('hashes').innerHTML=Object.entries(D.sourceHashes).map(([n,h])=>`<p>${esc(n)}</p><p class="hash">${h}</p>`).join('');
function stop(){clearInterval(timer);timer=null;$('play').textContent='▶ Reproducir';$('play').setAttribute('aria-label','Reproducir secuencia histórica');}
function chooseStation(id){if(!stationMap.has(id))throw new Error('Estación no válida');state.station=id;render();}
function chooseIndex(index){if(!Number.isInteger(index)||index<0||index>=D.times.length)throw new Error('Instante no válido');state.index=index;render();}
function showView(view){if(!['explorar','calidad','metodo'].includes(view))return;stop();state.view=view;document.querySelectorAll('.view').forEach(v=>v.hidden=v.id!==view);document.querySelectorAll('.nav').forEach(b=>{b.classList.toggle('active',b.dataset.view===view);if(b.dataset.view===view)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')});$('page-title').textContent={explorar:'Explorar resultados',calidad:'Calidad de datos',metodo:'Método y trazabilidad'}[view];}
function mapSvg(){const w=440,h=345,x=lon=>55+(lon+77.13)/.24*320,y=lat=>25+(-11.87-lat)/.38*260;let svg=`<svg class="chart" viewBox="0 0 ${w} ${h}" role="img" aria-label="Ubicación de siete estaciones de Lima; seleccionar un círculo cambia la estación"><title>Estaciones de Lima. El tamaño indica CO simulado, no concentración observada.</title>`;
for(const lat of [-11.9,-12,-12.1,-12.2]){svg+=`<line class="gridline" x1="48" x2="395" y1="${y(lat)}" y2="${y(lat)}"/><text x="3" y="${y(lat)+4}">${lat.toFixed(1)}°</text>`;}
for(const lon of [-77.1,-77,-76.9]){svg+=`<line class="gridline" y1="15" y2="310" x1="${x(lon)}" x2="${x(lon)}"/><text x="${x(lon)-20}" y="330">${lon.toFixed(1)}°</text>`;}
const offsets={CAMPO_DE_MARTE:[9,-12],CARABAYLLO:[-14,-20],SANTA_ANITA:[10,-7],SAN_BORJA:[-65,27],SAN_JUAN_DE_LURIGANCHO:[12,-14],SAN_MARTIN_DE_PORRES:[-5,-17],VILLA_MARIA_DEL_TRIUNFO:[-130,28]};
for(const s of D.stations){const r=records.get(`${s.id}|${D.times[state.index]}`),selected=s.id===state.station,rad=22*Math.sqrt(r.sim/maxSim),[ox,oy]=offsets[s.id]||[10,-10];svg+=`<circle class="map-point" tabindex="0" role="button" data-station="${s.id}" aria-label="${esc(s.name)}, CO simulado ${fmt(r.sim)} microgramos por metro cúbico" cx="${x(s.lon)}" cy="${y(s.lat)}" r="${rad}" fill="${selected?'#54dfc4':'#ffbb68'}" fill-opacity="${selected?'.85':'.45'}" stroke="${selected?'#c8fff2':'#ffbb68'}" stroke-width="${selected?2:1}"><title>${esc(s.name)} · ${fmt(r.sim)} µg/m³</title></circle><text class="map-label" x="${x(s.lon)+ox}" y="${y(s.lat)+oy}">${esc(s.name.replace('San Juan de Lurigancho','S. J. de Lurigancho').replace('San Martín de Porres','S. Martín de Porres').replace('Villa María del Triunfo','Villa María del Triunfo'))}</text>`;}
return svg+'</svg>';}
function seriesSvg(){const rs=D.times.map(t=>records.get(`${state.station}|${t}`)),w=650,h=310,l=56,r=12,top=22,bottom=40,ymax=Math.ceil(Math.max(...rs.flatMap(r=>[r.sim,r.obs??0]))/100)*100||100,x=i=>l+i/(rs.length-1)*(w-l-r),y=v=>top+(1-v/ymax)*(h-top-bottom);let svg=`<svg class="chart" viewBox="0 0 ${w} ${h}" role="img" aria-label="Serie de CO observado y simulado de agosto para ${esc(stationMap.get(state.station).name)}"><title>Las interrupciones de la curva observada indican datos faltantes</title>`;
for(let j=0;j<=4;j++){const v=ymax*j/4;svg+=`<line class="gridline" x1="${l}" x2="${w-r}" y1="${y(v)}" y2="${y(v)}"/><text x="${l-8}" y="${y(v)+4}" text-anchor="end">${fmt(v,0)}</text>`;}
for(const day of [1,8,15,22,31]){const i=(day-1)*8;svg+=`<text x="${x(i)}" y="${h-10}" text-anchor="middle">${day} ago</text>`;}
for(const [key,color,dash] of [['obs','#54dfc4',''],['sim','#ffbb68','5 4']]){let path='',open=false;rs.forEach((r,i)=>{if(r[key]==null){open=false;return;}path+=`${open?'L':'M'}${x(i).toFixed(2)},${y(r[key]).toFixed(2)} `;open=true});svg+=`<path d="${path}" stroke="${color}" stroke-width="2" stroke-dasharray="${dash}" fill="none"/>`;}
svg+=`<line x1="${x(state.index)}" x2="${x(state.index)}" y1="${top}" y2="${h-bottom}" stroke="#b1cbd7" stroke-dasharray="3 3"/>`;
for(const [key,color] of [['obs','#54dfc4'],['sim','#ffbb68']])if(rs[state.index][key]!=null)svg+=`<circle cx="${x(state.index)}" cy="${y(rs[state.index][key])}" r="4" fill="${color}"/>`;
return svg+'</svg>';}
function render(){const s=stationMap.get(state.station),t=D.times[state.index],r=records.get(`${s.id}|${t}`),m=metricMap.get(s.id);$('station').value=s.id;$('date').value=t.slice(0,10);$('hour').value=t.slice(11,13);$('timeline').value=state.index;$('time-label').textContent=`${t.slice(8,10)} ago 2018 · ${t.slice(11,16)}`;$('obs').textContent=fmt(r.obs);$('sim').textContent=fmt(r.sim);$('bias').textContent=fmt(m.bias);$('count').textContent=`${m.n} / 248`;$('coverage').textContent=`${fmt(m.coverage*100)} % con par numérico`;$('mae').textContent=fmt(m.mae);$('rmse').textContent=fmt(m.rmse);$('pearson').textContent=fmt(m.r,3);$('series-title').textContent=s.name;$('station-warning').hidden=!s.maintenance;$('station-warning').textContent='El boletín reporta mantenimiento en esta estación. No hay banderas horarias disponibles; sus resultados requieren cautela.';$('map').innerHTML=mapSvg();$('series').innerHTML=seriesSvg();document.querySelectorAll('#map-list button').forEach(b=>{b.classList.toggle('selected',b.dataset.station===s.id);b.setAttribute('aria-pressed',String(b.dataset.station===s.id))});}
document.querySelectorAll('.nav').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view)));
document.querySelector('.brand').addEventListener('click',e=>{e.preventDefault();showView('explorar')});
$('station').addEventListener('change',e=>{stop();chooseStation(e.target.value)});$('timeline').addEventListener('input',e=>{stop();chooseIndex(Number(e.target.value))});
function dateChange(){stop();const t=`${$('date').value} ${$('hour').value}:00:00`,i=D.times.indexOf(t);if(i>=0&&i>=(state.start??0)&&i<=(state.end??247))chooseIndex(i);else render();}
$('date').addEventListener('change',dateChange);$('hour').addEventListener('change',dateChange);
$('play').addEventListener('click',()=>{if(timer)return stop();if(state.index===247)chooseIndex(0);$('play').textContent='Ⅱ Pausar';$('play').setAttribute('aria-label','Pausar secuencia histórica');timer=setInterval(()=>{if(state.index>=247)return stop();chooseIndex(state.index+1);if(state.index===247)stop()},750)});
document.addEventListener('visibilitychange',()=>{if(document.hidden)stop()});
for(const el of [$('map'),$('map-list')]){el.addEventListener('click',e=>{const t=e.target.closest('[data-station]');if(t){stop();chooseStation(t.dataset.station)}});el.addEventListener('keydown',e=>{if(e.target.matches('circle[data-station]')&&['Enter',' '].includes(e.key)){e.preventDefault();stop();chooseStation(e.target.dataset.station)}});}
$('download').addEventListener('click',()=>{const s=stationMap.get(state.station);const lines=[['estacion','fecha_local_UTC_menos_5','fecha_UTC','CO_observado_ug_m3','CO_simulado_ug_m3_sup25C_1atm','CO_simulado_ppmv','par_numerico','advertencia_mantenimiento','estado'],...D.pairs.filter(r=>r.station===s.id).map(r=>[s.name,r.time,r.utc,r.obs??'',r.sim,r.ppm,r.valid,s.maintenance,'Preliminar: QA y referencia observada pendientes'])];const csv=lines.map(row=>row.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\r\n');const u=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=u;a.download=`CO_${s.id}_201808_preliminar.csv`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000)});
render();
if(document.modelContext?.registerTool){Promise.resolve(document.modelContext.registerTool({name:'consultar_estado_co',description:'Leer estación e instante seleccionados y sus valores históricos.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({...state,time:D.times[state.index],record:records.get(`${state.station}|${D.times[state.index]}`)})})).catch(()=>{});Promise.resolve(document.modelContext.registerTool({name:'seleccionar_estacion_co',description:'Cambiar la estación visible de la consulta histórica; no modifica datos originales.',inputSchema:{type:'object',properties:{station:{type:'string',enum:D.stations.map(s=>s.id)}},required:['station'],additionalProperties:false},execute:input=>{if(!input||!stationMap.has(input.station))throw new Error('Estación no válida');stop();chooseStation(input.station);return {station:state.station,time:D.times[state.index]}}})).catch(()=>{});}
