'use strict';
state.start=0;state.end=247;
let compareIds=['SANTA_ANITA','SAN_BORJA'],detailKey=null;
const originalRender=render,originalChooseIndex=chooseIndex;
const periodTimes=()=>D.times.slice(state.start,state.end+1);
const stationRows=id=>periodTimes().map(t=>records.get(`${id}|${t}`));
const periodLabel=()=>`${D.times[state.start].slice(0,10)} – ${D.times[state.end].slice(0,10)} · Lima (UTC−5)`;
const prettyTime=t=>`${t.slice(8,10)} ago · ${t.slice(11,16)}`;
const maxError=Math.max(...D.pairs.filter(r=>r.valid).map(r=>Math.abs(r.sim-r.obs)));
$('explorar').insertAdjacentHTML('afterbegin',`<div class="period-panel"><div><p class="eyebrow">PERÍODO DE ANÁLISIS</p><p class="caption">Las métricas, curvas, comparación y exportaciones se actualizan con este intervalo. Calidad de datos conserva el resumen mensual.</p></div><form id="period-form"><label>Desde<input id="from" type="date" min="2018-08-01" max="2018-08-31" value="2018-08-01" required></label><label>Hasta<input id="to" type="date" min="2018-08-01" max="2018-08-31" value="2018-08-31" required></label><button class="primary" type="submit">Aplicar intervalo</button><button class="secondary" id="reset-period" type="button">Mes completo</button></form><p id="period-error" class="error" role="alert" hidden></p><p id="active-period" class="caption" aria-live="polite"></p></div>`);
$('series').insertAdjacentHTML('afterend','<p class="caption">Selecciona la curva con el puntero o usa el calendario y la barra temporal para consultar un instante.</p><div id="point-detail" class="point-detail" aria-live="polite"></div>');
$('explorar').insertAdjacentHTML('beforeend',`<article class="panel analysis-panel"><div class="panel-heading"><div><p class="eyebrow">COMPARACIÓN ESPACIAL</p><h2>Estaciones en la misma escala</h2></div><button class="secondary" id="summary-download">Descargar resumen HTML</button></div><fieldset id="comparison-picks"><legend>Elige entre una y tres estaciones</legend>${D.stations.map(s=>`<label><input type="checkbox" value="${s.id}" ${compareIds.includes(s.id)?'checked':''}>${esc(s.name)}</label>`).join('')}</fieldset><p id="compare-error" class="error" role="alert" hidden></p><div id="comparison-charts"></div><div class="table-wrap"><table><caption id="compare-caption"></caption><thead><tr><th>Estación</th><th>Pares</th><th>Sesgo (µg/m³)</th><th>MAE (µg/m³)</th><th>RMSE (µg/m³)</th><th>r</th></tr></thead><tbody id="comparison-table"></tbody></table></div><p class="caption">Mismo intervalo y escala vertical. Cada estación usa sus propios pares disponibles; las diferencias de cobertura limitan la comparación. Las curvas no constituyen un ranking de calidad.</p></article><article class="panel analysis-panel"><p class="eyebrow">DIAGNÓSTICO DE ERRORES</p><h2>Residuo por estación e instante</h2><p class="caption">Simulado − observado · µg/m³. Cada columna es una salida de tres horas, sin promediar días. Selecciona una celda para ver sus valores.</p><div class="heat-legend"><span><i style="background:#ed9b42"></i> Subestimación</span><span><i style="background:#e6eef2"></i> Cero</span><span><i style="background:#46bce4"></i> Sobreestimación</span><span><i class="missing"></i> Sin par</span></div><p id="heat-scale" class="caption"></p><div class="heat-scroll" tabindex="0" aria-label="Tabla de residuos; desplazamiento horizontal disponible"><table id="heat-table"></table></div><div id="heat-detail" class="point-detail" aria-live="polite">Selecciona una celda del mapa de calor.</div></article>`);
document.querySelectorAll('#explorar .kpis p').forEach(p=>p.textContent=p.textContent.replace('mes completo','intervalo'));
document.querySelectorAll('#explorar .metric-strip span').forEach(p=>p.textContent=p.textContent.replace('mensual','del intervalo'));
document.querySelector('#series').parentElement.querySelectorAll('.caption').forEach(p=>{if(p.textContent.startsWith('Agosto completo'))p.textContent='Intervalo seleccionado · µg/m³. Línea vertical: instante elegido. Los vacíos no se interpolan.';if(p.textContent.startsWith('Los indicadores usan'))p.textContent='Los indicadores usan los pares numéricos del intervalo seleccionado. No representan únicamente el instante elegido.';});
function rowStats(id){return COAnalysis.stats(stationRows(id))}
function curveSvg(rows,ceiling,interactive=false){const w=650,h=interactive?310:230,l=58,right=18,top=22,bottom=40,imax=rows.length-1,x=i=>l+i/imax*(w-l-right),y=v=>top+(1-v/ceiling)*(h-top-bottom);let svg=`<svg class="chart period-chart" viewBox="0 0 ${w} ${h}" role="img" aria-label="CO observado y simulado en el intervalo, ${esc(stationMap.get(rows[0].station).name)}"><title>Observado en verde, simulado en naranja; vacíos sin interpolar</title>`;
 for(let k=0;k<=4;k++){const v=ceiling*k/4;svg+=`<line class="gridline" x1="${l}" x2="${w-right}" y1="${y(v)}" y2="${y(v)}"/><text x="${l-8}" y="${y(v)+4}" text-anchor="end">${fmt(v,0)}</text>`;}
 for(const i of [...new Set([0,Math.round(imax/3),Math.round(imax*2/3),imax])])svg+=`<text x="${x(i)}" y="${h-12}" text-anchor="${i===0?'start':i===imax?'end':'middle'}">${prettyTime(rows[i].time)}</text>`;
 for(const [key,color,dash] of [['obs','#54dfc4',''],['sim','#ffbb68','5 4']]){let path='',open=false;rows.forEach((r,i)=>{if(r[key]==null){open=false;return}path+=`${open?'L':'M'}${x(i).toFixed(2)},${y(r[key]).toFixed(2)} `;open=true});svg+=`<path d="${path}" fill="none" stroke="${color}" stroke-width="2" stroke-dasharray="${dash}"/>`;rows.forEach((r,i)=>{if(r[key]!=null)svg+=`<circle cx="${x(i)}" cy="${y(r[key])}" r="${rows.length<=32?3:1.6}" fill="${color}"/>`});}
 if(interactive){const index=state.index-state.start;svg+=`<line x1="${x(index)}" x2="${x(index)}" y1="${top}" y2="${h-bottom}" stroke="#b1cbd7" stroke-dasharray="3 3"/>`;
 rows.forEach((r,i)=>{const step=(w-l-right)/imax;svg+=`<rect data-index="${i+state.start}" x="${Math.max(l,x(i)-step/2)}" y="${top}" width="${Math.min(step,w-right-Math.max(l,x(i)-step/2))}" height="${h-top-bottom}" fill="transparent"><title>${prettyTime(r.time)} · Observado ${fmt(r.obs)} · Simulado ${fmt(r.sim)} µg/m³</title></rect>`;});}
 return svg+'</svg>';}
seriesSvg=function(){const rows=stationRows(state.station),max=Math.max(...rows.flatMap(r=>[r.obs??0,r.sim]));return curveSvg(rows,Math.ceil(max/100)*100||100,true)};
function detail(r){const s=stationMap.get(r.station);return `<strong>${esc(s.name)} · ${prettyTime(r.time)}</strong><div class="detail-grid"><span>Observado<strong>${fmt(r.obs)} µg/m³</strong></span><span>Simulado<strong>${fmt(r.sim)} µg/m³</strong></span><span>Residuo<strong>${r.valid?fmt(r.sim-r.obs):'Sin par'}${r.valid?' µg/m³':''}</strong></span></div><p class="caption">${r.valid?'Par numérico disponible; QA horario pendiente.':'No existe par numérico. No se calcula un residuo.'} ${s.maintenance?'Advertencia de mantenimiento reportada.':''} UTC: ${esc(r.utc)}. Conversión simulada provisional: 25 °C y 1 atm.</p>`}
function paintComparison(){const ceiling=Math.ceil(Math.max(...compareIds.flatMap(id=>stationRows(id).flatMap(r=>[r.obs??0,r.sim])))/100)*100||100;
 $('comparison-charts').innerHTML=compareIds.map(id=>`<section><h3>${esc(stationMap.get(id).name)}</h3><p class="caption">µg/m³ · <span class="cyan">━ Observado</span> <span class="orange">┄ Simulado</span></p>${curveSvg(stationRows(id),ceiling)}</section>`).join('');
 $('compare-caption').textContent=periodLabel();$('comparison-table').innerHTML=compareIds.map(id=>{const m=rowStats(id),s=stationMap.get(id);return `<tr><td>${esc(s.name)}${s.maintenance?' *':''}</td><td>${m.n} / ${m.possible}</td><td>${fmt(m.bias)}</td><td>${fmt(m.mae)}</td><td>${fmt(m.rmse)}</td><td>${fmt(m.r,3)}</td></tr>`}).join('');}
function heatColor(e){if(e==null)return '';const a=Math.sqrt(Math.min(1,Math.abs(e)/maxError)),c=e<0?[237,155,66]:[70,188,228],zero=[230,238,242];return `rgb(${c.map((v,i)=>Math.round(zero[i]+(v-zero[i])*a)).join(',')})`;}
function paintHeat(){const times=periodTimes();$('heat-scale').textContent=`Escala fija para todo agosto: −${fmt(maxError,0)} a +${fmt(maxError,0)} µg/m³. Intensidad de color transformada con raíz cuadrada para distinguir errores pequeños. * Mantenimiento reportado.`;
 $('heat-table').innerHTML=`<caption>Residuos · ${esc(periodLabel())}</caption><thead><tr><th scope="col">Estación</th>${times.map(t=>`<th scope="col">${t.slice(8,10)} ago<br>${t.slice(11,16)}</th>`).join('')}</tr></thead><tbody>${D.stations.map(s=>`<tr><th scope="row">${esc(s.name)}${s.maintenance?' *':''}</th>${times.map(t=>{const r=records.get(`${s.id}|${t}`),e=r.valid?r.sim-r.obs:null;return `<td><button data-station="${s.id}" data-time="${t}" class="heat-cell ${e==null?'missing':''}" style="${e==null?'':`background:${heatColor(e)}`}" aria-label="${esc(s.name)}, ${prettyTime(t)}, ${e==null?'sin par':`residuo ${fmt(e)} µg/m³`}" title="${e==null?'Sin par':fmt(e)+' µg/m³'}">${e==null?'—':fmt(e,0)}</button></td>`}).join('')}</tr>`).join('')}</tbody>`;}
render=function(){originalRender();const m=rowStats(state.station);$('bias').textContent=fmt(m.bias);$('count').textContent=`${m.n} / ${m.possible}`;$('coverage').textContent=`${fmt(m.coverage*100)} % con par numérico`;$('mae').textContent=fmt(m.mae);$('rmse').textContent=fmt(m.rmse);$('pearson').textContent=fmt(m.r,3);$('timeline').min=state.start;$('timeline').max=state.end;$('date').min=D.times[state.start].slice(0,10);$('date').max=D.times[state.end].slice(0,10);$('active-period').textContent=`Intervalo activo: ${periodLabel()} · ${m.possible} instantes programados por estación.`;$('point-detail').innerHTML=detail(records.get(`${state.station}|${D.times[state.index]}`));};
chooseIndex=function(index){if(index<state.start||index>state.end)throw new Error('Instante fuera del intervalo');originalChooseIndex(index)};
function applyPeriod(start,end){const bounds=COAnalysis.interval(D.times,start,end);stop();Object.assign(state,bounds);state.index=Math.max(state.start,Math.min(state.end,state.index));$('from').value=start;$('to').value=end;$('period-error').hidden=true;render();paintComparison();paintHeat();$('heat-detail').textContent='Selecciona una celda del mapa de calor.';detailKey=null;}
$('period-form').addEventListener('submit',e=>{e.preventDefault();try{applyPeriod($('from').value,$('to').value)}catch(err){$('period-error').hidden=false;$('period-error').textContent=err.message}});
$('reset-period').addEventListener('click',()=>applyPeriod('2018-08-01','2018-08-31'));
$('series').addEventListener('click',e=>{const p=e.target.closest('[data-index]');if(p){stop();chooseIndex(Number(p.dataset.index))}});
$('comparison-picks').addEventListener('change',e=>{const id=e.target.value,next=[...document.querySelectorAll('#comparison-picks input:checked')].map(c=>c.value);if(next.length<1||next.length>3){e.target.checked=compareIds.includes(id);$('compare-error').hidden=false;$('compare-error').textContent='Selecciona entre una y tres estaciones.';return;}compareIds=next;$('compare-error').hidden=true;paintComparison();});
$('heat-table').addEventListener('click',e=>{const b=e.target.closest('[data-time]');if(!b)return;stop();state.station=b.dataset.station;state.index=D.times.indexOf(b.dataset.time);render();detailKey=`${b.dataset.station}|${b.dataset.time}`;$('heat-detail').innerHTML=detail(records.get(detailKey));});
function saveFile(name,text,type){const u=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),2000)}
function summaryHtml(){const rows=compareIds.map(id=>{const s=stationMap.get(id),m=rowStats(id);return `<tr><td>${esc(s.name)}</td><td>${m.n}/${m.possible}</td><td>${fmt(m.bias)}</td><td>${fmt(m.mae)}</td><td>${fmt(m.rmse)}</td><td>${fmt(m.r,3)}</td><td>${s.maintenance?'Mantenimiento reportado':'Sin advertencia reportada'}</td></tr>`}).join('');return `<!doctype html><html lang="es"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Resumen CO Lima</title><style>body{font:16px/1.6 system-ui;max-width:1000px;margin:40px auto;padding:20px;color:#142c3d}table{border-collapse:collapse;width:100%;font-size:14px}th,td{text-align:left;padding:10px;border:1px solid #ccd5da}small{overflow-wrap:anywhere}h1{color:#126d67}@media print{body{margin:0}}</style><h1>CO Lima · resumen de evaluación inicial</h1><p><strong>${esc(periodLabel())}</strong></p><p>${esc(D.version)}</p><p>Reproducción histórica, no pronóstico ni alerta operativa. Estaciones seleccionadas en la comparación.</p><div style="overflow:auto"><table><tr><th>Estación</th><th>Pares</th><th>Sesgo µg/m³</th><th>MAE µg/m³</th><th>RMSE µg/m³</th><th>r</th><th>Advertencia</th></tr>${rows}</table></div><h2>Método y límites</h2><ul><li>Sesgo = simulado − observado. Indicadores calculados sobre los pares numéricos disponibles de cada estación, sin rellenar vacíos.</li><li>r no se calcula con menos de dos pares o varianza nula. Sin dato no significa cero.</li><li>Salidas WRF cada tres horas frente a observaciones horarias; no son necesariamente promedios equivalentes.</li><li>CO simulado convertido a 25 °C y 1 atm. Referencia termodinámica y QA horario del archivo observado pendientes.</li><li>Las diferencias de cobertura limitan las comparaciones entre estaciones. Mantenimiento no implica que todos los registros sean inválidos.</li><li>WRF 4.4, CHEM_TRACER, d02 de 3 km; ERA5, emisiones HTAP v3 y condiciones CO CAMS EAC4. No química atmosférica completa.</li></ul><h2>Fuentes</h2><p><a href="https://www.datosabiertos.gob.pe/sites/default/files/datos_horarios_contaminacion_lima.csv">Observaciones, Datos Abiertos Perú</a><br><a href="https://www.senamhi.gob.pe/load/file/03201SENA-62.pdf">Boletín SENAMHI, agosto 2018</a></p><h2>Trazabilidad</h2>${Object.entries(D.sourceHashes).map(([n,h])=>`<p>${esc(n)}<br><small>SHA-256: ${h}</small></p>`).join('')}</html>`;}
$('summary-download').addEventListener('click',()=>saveFile(`Resumen_CO_${D.times[state.start].slice(0,10)}_${D.times[state.end].slice(0,10)}.html`,summaryHtml(),'text/html;charset=utf-8'));
// Replace only the old export button to remove its whole-month handler.
const oldDownload=$('download'),newDownload=oldDownload.cloneNode(true);oldDownload.replaceWith(newDownload);
newDownload.textContent='Descargar CSV del intervalo ↗';newDownload.addEventListener('click',()=>{const s=stationMap.get(state.station),rows=[['estacion','fecha_local_UTC_menos_5','fecha_UTC','CO_observado_ug_m3','CO_simulado_ug_m3_sup25C_1atm','par_numerico','advertencia_mantenimiento','estado'],...stationRows(s.id).map(r=>[s.name,r.time,r.utc,r.obs??'',r.sim,r.valid,s.maintenance,'Preliminar: QA y referencia observada pendientes'])];saveFile(`CO_${s.id}_${D.times[state.start].slice(0,10)}_${D.times[state.end].slice(0,10)}.csv`,'\ufeff'+rows.map(row=>row.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\r\n'),'text/csv;charset=utf-8');});
// Playback uses interval bounds and always stops at its last sample.
const oldPlay=$('play'),newPlay=oldPlay.cloneNode(true);oldPlay.replaceWith(newPlay);newPlay.addEventListener('click',()=>{if(timer)return stop();if(state.index>=state.end)chooseIndex(state.start);newPlay.textContent='Ⅱ Pausar';newPlay.setAttribute('aria-label','Pausar secuencia histórica');timer=setInterval(()=>{if(state.index>=state.end)return stop();chooseIndex(state.index+1);if(state.index===state.end)stop()},750)});
render();paintComparison();paintHeat();
