/* Educational view only. Does not alter simulation data or metric calculations. */
(() => {
 'use strict';
 const root=document.getElementById('metodo');
 const steps=[
  {name:'Reunir',title:'Tres entradas para el modelo; una referencia para contrastarlo',question:'¿Qué necesitamos conocer sobre Lima?',text:'El tiempo atmosférico mueve el CO; las emisiones lo incorporan al aire; el fondo describe el CO que ya existe y entra al dominio. Las estaciones aportan observaciones para comparar después.',input:'ERA5 + HTAP v3 + CAMS EAC4',output:'Meteorología, emisiones y condiciones de CO',example:'SENAMHI no alimenta una corrección automática del modelo: sus registros se usan como referencia observada.',limit:'Un inventario de emisiones no es una medición de la concentración en una calle.',terms:'ERA5: reconstrucción meteorológica. HTAP: inventario de emisiones. CAMS: reanálisis de composición atmosférica.'},
  {name:'Preparar',title:'Poner las fuentes en un marco común',question:'¿Cómo hacemos compatibles datos distintos?',text:'Se preparan los campos para las mallas del modelo, sus niveles y tiempos. Se tratan las unidades y los niveles de CAMS situados bajo el terreno. Las emisiones mensuales permanecen constantes dentro de cada mes.',input:'Campos con resoluciones y formatos diferentes',output:'Entradas compatibles con WRF',example:'El dominio exterior tiene celdas de 9 km y el interior, centrado en el área de estudio, de 3 km. Una celda no representa una calle.',limit:'La inyección de emisiones es superficial. No se resuelven los cañones urbanos ni las alturas específicas de cada chimenea.',terms:'Malla: división del territorio en celdas. Condición de frontera: información que entra por los bordes del dominio.'},
  {name:'Simular',title:'Reconstruir el transporte histórico del CO',question:'¿Qué hace WRF en este proyecto?',text:'WRF 4.4, configurado como trazador de CO, calcula su evolución sobre el territorio. La ejecución empieza el 30 de julio y termina el 1 de septiembre de 2018; la evaluación presentada corresponde a agosto, en hora de Lima.',input:'Meteorología + emisiones + CO inicial y de frontera',output:'Archivos NetCDF con campos de CO',example:'La web reproduce 248 instantes históricos separados por 3 horas. Al pulsar reproducir no se ejecuta una nueva simulación.',limit:'No es una simulación completa de aerosoles, un pronóstico operativo ni una medición en tiempo real.',terms:'Trazador: sustancia cuyo transporte se sigue en el modelo. NetCDF: formato de datos científicos multidimensionales.'},
  {name:'Contrastar',title:'Comparar el mismo lugar y el mismo instante',question:'¿Se parece lo simulado a lo observado?',text:'Se extrae la primera capa del modelo en la celda más cercana a cada estación con coordenadas verificadas. Se alinean las fechas en UTC−5 y se comparan los valores numéricos disponibles, sin rellenar los vacíos con ceros.',input:'CO simulado + observaciones de 7 estaciones',output:'1.322 pares de 1.736 combinaciones posibles',example:'Ejemplo ilustrativo: si el modelo da 100 y la estación 150 µg/m³, el residuo es −50 µg/m³. El modelo subestima ese instante.',limit:'La conversión a µg/m³ usa provisionalmente 25 °C y 101.325 Pa. Falta confirmar la referencia observada y la equivalencia entre salida instantánea y registro horario.',terms:'Par: un valor observado y uno simulado para una estación y fecha. Sesgo: promedio de los residuos, con su signo.'},
  {name:'Explorar',title:'Transformar resultados en información consultable',question:'¿Qué aporta la plataforma?',text:'Python prepara productos reducidos para la web: mapas, series, indicadores y tablas. La plataforma permite examinar el mes y sus limitaciones sin volver a ejecutar WRF.',input:'Resultados procesados y controles documentados',output:'Exploración, comparación y descarga de series',example:'La extensión PM₂.₅ prueba una relación empírica con CO: se ajusta del 1 al 20 de agosto y se evalúa del 21 al 31 frente a una referencia horaria.',limit:'Solo una de seis estaciones evaluables mejora en la prueba final de PM₂.₅, sin ventaja estable entre bloques. Es exploratorio, no química de partículas validada.',terms:'Trazabilidad: poder identificar de dónde viene un resultado y qué transformaciones recibió.'}
 ];
 root.querySelector('.section-intro').remove();root.querySelector('.pipeline').remove();
 const technical=root.querySelector('.two-col');
 const details=document.createElement('details');details.className='method-technical panel';
 details.innerHTML='<summary>Consultar la ficha técnica y los límites del modelo</summary>';
 technical.before(details);details.appendChild(technical);
 const intro=document.createElement('div');intro.className='method-story';
 intro.innerHTML=`<header class="method-hero"><p class="eyebrow">DEL DATO A LA EVIDENCIA</p><h2>¿Cómo construimos esta mirada de Lima?</h2><p>Recorre el camino de una simulación histórica: de las fuentes originales a los resultados que puedes explorar. Cada etapa muestra qué entra, qué sale y qué no podemos afirmar.</p><div class="method-facts"><span>01 mes estudiado · agosto 2018</span><span>07 estaciones comparadas</span><span>CO como trazador</span></div></header>
 <nav class="method-steps" aria-label="Etapas del método">${steps.map((s,i)=>`<button type="button" data-step="${i}" aria-pressed="${i===0}"><span>0${i+1}</span>${s.name}</button>`).join('')}</nav>
 <article class="method-stage panel" aria-labelledby="method-stage-title"><div id="method-stage-body" aria-live="polite" aria-atomic="true"></div><div class="method-controls"><button type="button" id="method-prev">← Anterior</button><span id="method-progress"></span><button type="button" id="method-next">Siguiente →</button></div></article>
 <div class="method-bottom"><article class="panel"><p class="eyebrow">EL VÍNCULO CON UN GEMELO DIGITAL</p><h2>Una base, no una réplica en tiempo real</h2><p>El aporte es conectar datos del territorio, un modelo y una interfaz de consulta reproducible. Todavía no existe sincronización continua y bidireccional con la ciudad.</p><div class="method-boundary"><strong>Implementado</strong><span>Integración → simulación → evaluación → visualización</span></div><div class="method-boundary pending"><strong>No demostrado</strong><span>Pronóstico validado, alertas operativas y actualización en vivo</span></div></article>
 <article class="panel"><p class="eyebrow">LEE LOS RESULTADOS CON CRITERIO</p><h2>Tres preguntas clave</h2><details><summary>¿Un mapa de color muestra riesgo para la salud?</summary><p>No. Muestra concentración simulada en la malla. No equivale a exposición personal ni justifica una alerta sanitaria.</p></details><details><summary>¿Tener datos significa que el modelo está validado?</summary><p>No. Disponibilidad, calidad de la observación y desempeño del modelo son aspectos distintos. Los 1.322 pares son comparaciones numéricas, no certificaciones de calidad.</p></details><details><summary>¿El CO se transforma en PM₂.₅?</summary><p>No en este modelo. La pestaña PM₂.₅ evalúa una estimación estadística exploratoria; no representa la formación física o química de partículas.</p></details></article></div>`;
 root.prepend(intro);
 let current=0;
 function render(i){current=i;const s=steps[i];
  document.getElementById('method-stage-body').innerHTML=`<p class="eyebrow">ETAPA 0${i+1} / ${s.question}</p><h2 id="method-stage-title">${s.title}</h2><p class="method-explanation">${s.text}</p><div class="method-flow"><div><small>ENTRA</small><strong>${s.input}</strong></div><span aria-hidden="true">→</span><div><small>SE OBTIENE</small><strong>${s.output}</strong></div></div><div class="method-example"><strong>Para entenderlo</strong><p>${s.example}</p></div><p class="method-limit"><strong>Límite importante · </strong>${s.limit}</p><details><summary>Palabras técnicas, en sencillo</summary><p>${s.terms}</p></details>`;
  intro.querySelectorAll('[data-step]').forEach((b,n)=>b.setAttribute('aria-pressed',String(n===i)));
  document.getElementById('method-progress').textContent=`${i+1} de ${steps.length}`;
  document.getElementById('method-prev').disabled=i===0;document.getElementById('method-next').disabled=i===steps.length-1;
 }
 intro.querySelectorAll('[data-step]').forEach(b=>b.addEventListener('click',()=>render(Number(b.dataset.step))));
 document.getElementById('method-prev').addEventListener('click',()=>{if(current>0)render(current-1)});
 document.getElementById('method-next').addEventListener('click',()=>{if(current<steps.length-1)render(current+1)});
 root.querySelector('.sources h2').textContent='Comprueba el origen de los resultados';
 const explanation=document.createElement('p');explanation.textContent='Las fuentes explican el origen de los datos. Las huellas SHA-256 identifican las tablas utilizadas: permiten comprobar si un archivo cambió, pero no certifican su calidad científica.';
 root.querySelector('.sources h2').after(explanation);
 render(0);
})();
